### ISSUE TITLE
피드백 - 박가현 튜터

### ISSUE THREAD

**Issue by hyun2e** [seopport/TinyCuteLetterbox#1]
안녕하세요, 지원님!
과제 구현하시느라 정말 고생 많으셨습니다.
전체적으로 아쉬운 부분이 거의 없을 정도로 과제 완성도가 매우 높아 열심히 공부하신 것이 빛을 발하고 있는 것 같습니다 :)
또한 readme에 기능 정리와 트러블 슈팅까지 깔끔하게 정리하신 부분이 인상깊었습니다. 
추후 프로젝트를 복기할 때나 포트폴리오를 작성하실 때 유용할 것 같습니다.

#Props Drilling
<잘 구현된 부분>
- 데이터 fetch, state와 set 함수를 적절한 곳에서 실행하고 선언하여 전체적인 컴포넌트 구조를 효율적으로 잘 짜셨습니다.
https://github.com/seopport/TinyCuteLetterbox/blob/495de0bc55b2e3669fbe321e3d896baca2a54c5a/src/shared/router.js#L7-L20

#Context Api
<잘 구현된 부분>
- context api의 사용 방법과 개념을 이해하고 올바른 방법으로 적용하였습니다.
https://github.com/seopport/TinyCuteLetterbox/blob/30d8d97772f689ddcbf536dacab4ff1e9fbdcc92/src/shared/router.js#L24-L36

#Redux(redux 브랜치 기준)
<잘 구현된 부분>
- redux의 개념을 잘 이해하고 올바르게 사용하였습니다.
https://github.com/seopport/TinyCuteLetterbox/blob/27766cd63b52f85d571c30c13c7c78f795f5b586/src/components/Home/LetterBoxSelecter.jsx#L41-L48

<아쉬운 부분>
- 리덕스 모듈에서 보통 액션 타입의 이름은 카멜 케이스보다는 대문자, 스네이크 케이스(SEND_LETTER)를 많이 사용합니다.
https://ko.redux.js.org/usage/structuring-reducers/basic-reducer-structure
https://github.com/seopport/TinyCuteLetterbox/blob/27766cd63b52f85d571c30c13c7c78f795f5b586/src/store/redux/modules/letters.js#L3-L4
- 비즈니스 로직 같은 경우는 reducer에서 구현해주시면 코드 재사용성이 더 높아집니다.
https://github.com/seopport/TinyCuteLetterbox/blob/27766cd63b52f85d571c30c13c7c78f795f5b586/src/components/Detail/LetterDetailView.jsx#L176-L218
- context api를 사용하지 않음에도 context 폴더가 남아있습니다. 리덕스 프로젝트에서는 쓰지 않기 때문에 정리해주시는 것이 좋습니다.
- 불필요한 주석은 구현을 마무리 할 때 삭제하면서 코드를 정리해주는 것이 좋습니다.
https://github.com/seopport/TinyCuteLetterbox/blob/27766cd63b52f85d571c30c13c7c78f795f5b586/src/shared/router.js#L8-L21

**Comment by seopport** [comment]
리뷰 감사합니다 튜터님 🙇‍♀️
